version: '3.8'
name: montra
services:
    api:
        container_name: montra-api
        build:
            context: ./
            dockerfile: ./Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80
